#!/bin/bash


if [[ -z $1 ]]; then
  echo need device id, 0, etc
  exit 1
fi

if [[ -z $2 ]]; then
  echo need dump start addr
  exit 1
fi

if [[ -z $3 ]]; then
  echo need size
  exit 1
fi

sudo efsmt -d $1 -dmem dump $2 $3|tail -n +6 |awk '{print $3}'|dmaster
