#!/bin/bash
if [ -z $1 ]; then
  exit 0
fi
INPUT=$1
if [[ ! -f ${INPUT} ]]; then
  echo ${INPUT} not exists 1>&2
  exit 1
fi
DM=$(which dmaster)
if [ -z $DM ]; then
  echo no dmaster 1>&2
  exit 1
fi

RFILE=$(mktemp)
SOUT="cqms.txt"

${DM} -i20 ${INPUT} > ${RFILE}
if [[ x$? != x0 ]]; then
  echo error dmaster go 1>&2
  exit 1
fi

cat ${RFILE} |grep ^CQM > ${SOUT}
echo "#statistics for events for CQM:"
cat ${SOUT}|awk '{print $5}'|sort -u

echo "# statistics for CQM distribution"
cat ${SOUT}|awk '{print $1,$2,$3,$4,$5}'|sort -u

