#!/bin/bash

# default to dorado
ARCH="-i20"

TY=$1
case x${TY} in
xt20|xpavo)
  ARCH="-t20"
  shift
;;
xi20|xdorado)
  ARCH="-i20"
  shift
;;
*)
;;
esac

if [ -z $1 ]; then
  echo need input
  exit 0
fi


INPUT=$1
if [[ ! -f ${INPUT} ]]; then
  echo ${INPUT} not exists 1>&2
  exit 1
fi
DM=$(which dmaster)
if [ -z $DM ]; then
  echo no dmaster 1>&2
  exit 1
fi

RFILE=$(mktemp)
SOUT="sips.txt"

${DM} ${ARCH} ${INPUT} > ${RFILE}
if [[ x$? != x0 ]]; then
  echo error dmaster procesing 1>&2
  exit 1
fi

cat ${RFILE} |grep ^SIP > ${SOUT}
echo "#statistics for events for SIP:"
cat ${SOUT}|awk '{print $5}'|sort -u

echo "# statistics for SIP distribution"
cat ${SOUT}|awk '{print $1,$2,$3,$4,$5}'|sort -u

echo "# statistics for SIP PIDs"
cat ${SOUT}|awk '{print $6}'|sort -u
