#!/bin/bash

# default to dorado
ARCH="-dump"

TY=$1
case x${TY} in
xt20|xpavo)
  ARCH="-t20"
  shift
;;
xi20|xdorado)
  ARCH="-i20"
  shift
;;
*)
;;
esac

RAWOPT=$1
if [[ x${RAWOPT} == xraw ]]; then
	shift
	RAWOPT="-rawdpf"
else
	RAWOPT=""
fi

if [ -z $1 ]; then
  echo need input rawfile 1>&2
  exit 0
fi

INPUT=$1
if [[ ! -f ${INPUT} ]]; then
  echo ${INPUT} not exists 1>&2
  exit 1
fi
DM=$(which dmaster)
if [ -z $DM ]; then
  echo no dmaster 1>&2
  exit 1
fi

RFILE=$(mktemp)
SOUT="sips.txt"

${DM} ${ARCH} ${RAWOPT} ${INPUT} > ${RFILE}
if [[ x$? != x0 ]]; then
  echo error dmaster procesing 1>&2
  exit 1
fi

echo "# engines:"
cat ${RFILE}|awk '{print $1}'|sort -u
