#!/bin/bash

if [ -z $1 ]; then
  echo need input 1>&2
  exit 1
fi

INPUT=$1


gen_src() {
  cat <<EOF
select name, engine_id from kernel;
EOF
}

SRC0=$(mktemp)
echo $(gen_src) > ${SRC0}
sqlite3 $INPUT < ${SRC0}

