#!/bin/bash

EOPT="--nc"
DEVID=$1
if [[ -z ${DEVID} ]]; then
  echo need device id, 0, etc
  exit 1
fi

START=$(efsmt ${EOPT} -d ${DEVID} -reg TS.*DPF_RING*|grep DPF_RING_BASE_LOW|awk '{print $NF}')
if [[ -z ${START} ]]; then
  echo need dump start addr
  exit 1
fi

PROD=$(efsmt ${EOPT} -d ${DEVID} -reg TS.*DPF_RING*|grep DPF_RING_PROD|awk '{print $NF}')
if [[ -z ${PROD} ]]; then
  echo size parsing error
  exit 1
fi

echo ${RPOD}
PRODx4="0x$(python3 -c "print('%x' % (int('${PROD}', 16) * 4))")"

echo \# dump from ${START} for ${PRODx4}

sudo efsmt -d ${DEVID} -dmem dump ${START} ${PRODx4}|tail -n +6 |awk '{print $4}'|dmaster|sort -u
